### ISSUE TITLE
Display the correct state in navigation bar destinations

### ISSUE THREAD

**Issue by etonotieno** [etonotieno/GoCart#148]
The navigation bar icons, actions, and title should be remembered as a state and should change depending on the current screen.

Favourites Screen -> 
![Wishlist -Empty State](https://github.com/etonotieno/GoCart/assets/25648109/a515be59-867d-4c95-ba6a-087ddd1fe764)

Home Screen -> 
![image](https://github.com/etonotieno/GoCart/assets/25648109/e1d91335-b30a-4269-8b84-d939ca9ccc95)

**Comment by joelkanyi** [comment]
Hey @etonotieno , I'd like to help with this issue, but I don't understand what is wrong. Can you explain it a bit further?

**Comment by etonotieno** [comment]
Currently, the same "GoCart" icon/title is displayed for each bottom bar destination but this should change on each destination. For example when the user navigates to the "Favorites" screen, the title should be "Favorites" @joelkanyi

**Comment by joelkanyi** [comment]
Now I get it, can you assign me the issue. also please indicate what should appear on each bottom bar item

**Comment by etonotieno** [comment]
| Item      | Title | Icons | 
| ----------- | ----------- |  ----------- |
| Home      | GoCart icon/title       | Search, ShoppingCart |
| Services      | Services     | None |
| Orders      | My Orders     | None |
| Favorites      | Favorites     | Search, ShoppingCart |

**Comment by joelkanyi** [comment]
Hey @etonotieno, should the navigation drawer icon appear on all bottom nav items or only on the home screen?

**Comment by etonotieno** [comment]
Hi @joelkanyi, the drawer icon appears on all bottom nav items
